#name: github pages
#
#on:
#  push:
#    branches:
#      - main  # Set a branch to deploy
#
#jobs:
#  deploy:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: true  # Fetch Hugo themes (true OR recursive)
#          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
#
#      - name: Setup Hugo
#        uses: peaceiris/actions-hugo@v2
#        with:
#          hugo-version: 'latest'
#          # extended: true
#
#      - name: Build
#        run: hugo --minify
#
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./public
#

name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
